CREATE TABLE DERIVADAS_RESULTADO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FECHA_REGISTRO DATE,
    FUNCION VARCHAR2(100),
    RESULTADO1 NUMBER,
    RESULTADO2 NUMBER,
    RESULTADO3 NUMBER,
    RESULTADO4 NUMBER,
    RESULTADO5 NUMBER,
    RESULTADO6 NUMBER
);

CREATE OR REPLACE PROCEDURE SP_GUARDAR_DERIVADA (
    P_FUNCION    IN VARCHAR2,
    P_R1         IN NUMBER,
    P_R2         IN NUMBER,
    P_R3         IN NUMBER,
    P_R4         IN NUMBER,
    P_R5         IN NUMBER,
    P_R6         IN NUMBER
) AS
BEGIN
    INSERT INTO DERIVADAS_RESULTADO (
        FECHA_REGISTRO,
        FUNCION,
        RESULTADO1,
        RESULTADO2,
        RESULTADO3,
        RESULTADO4,
        RESULTADO5,
        RESULTADO6
    ) VALUES (
        SYSDATE,
        P_FUNCION,
        P_R1,
        P_R2,
        P_R3,
        P_R4,
        P_R5,
        P_R6
    );

    COMMIT;
END;
/

COMMIT;